// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJC_rh3n_inbORS2qq2-uL_It6IOtdRPY',
    appId: '1:290872068278:web:7fc8c358d1d43e6f097e17',
    messagingSenderId: '290872068278',
    projectId: 'flutter-firestore-93695',
    authDomain: 'flutter-firestore-93695.firebaseapp.com',
    storageBucket: 'flutter-firestore-93695.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd6BIiy9spyGPe6tEqN6GupnyyCDeZNow',
    appId: '1:290872068278:android:f4411b2f0c3342ce097e17',
    messagingSenderId: '290872068278',
    projectId: 'flutter-firestore-93695',
    storageBucket: 'flutter-firestore-93695.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABA4WUo2oO2EEEY8Nv_P9IkmA_PJhT6LA',
    appId: '1:290872068278:ios:2e28549aa4899b7a097e17',
    messagingSenderId: '290872068278',
    projectId: 'flutter-firestore-93695',
    storageBucket: 'flutter-firestore-93695.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABA4WUo2oO2EEEY8Nv_P9IkmA_PJhT6LA',
    appId: '1:290872068278:ios:2e28549aa4899b7a097e17',
    messagingSenderId: '290872068278',
    projectId: 'flutter-firestore-93695',
    storageBucket: 'flutter-firestore-93695.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJC_rh3n_inbORS2qq2-uL_It6IOtdRPY',
    appId: '1:290872068278:web:cd013a96f4a4c840097e17',
    messagingSenderId: '290872068278',
    projectId: 'flutter-firestore-93695',
    authDomain: 'flutter-firestore-93695.firebaseapp.com',
    storageBucket: 'flutter-firestore-93695.firebasestorage.app',
  );
}
